version: "3"

services:
  node:
    build: .
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./:/var/www/html
    command: bash -c "npm install && npm run dev"
  redis:
    image: redis:5
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  arangodata:
  arangoconfig:
